server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://120.48.4.19:3306/my_database?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: gjl123
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.144.230.45
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
  cloud:
    nacos:
      discovery:
        server-addr: 192.144.230.45:8848   # Nacos 服务地址
        namespace: public                 # 命名空间ID，默认 public
        group: DEFAULT_GROUP              # 服务分组，默认即可
      username: nacos                  # 如果开启权限认证
      password: nacos
  application:
    name: springboot_test
  quartz:
    job-store-type: jdbc            # 用数据库持久化（生产建议）
    jdbc:
      initialize-schema: always     # 第一次启动自动初始化 Quartz 表
    properties:
      org:
        quartz:
          scheduler.instanceName: appScheduler
          threadPool.threadCount: 10
  redis:
    host: 192.144.230.45   # Redis服务器地址
    port: 6379        # Redis端口
    password: redis
    database: 0       # 默认数据库
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springboot_test.entity
  configuration:
    map-underscore-to-camel-case: true
    # 控制台打印 SQL（开发环境用）
db:
  url: jdbc:mysql://192.168.2.244:3306/crm?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  username: root
  password: gjl123
